// List
export const FETCH_ALL_LISTS = "FETCH_ALL_LISTS";
export const ADD_NEW_LIST = "ADD_NEW_LIST";
export const ADD_NEW_CARD_TO_LIST = "ADD_NEW_CARD_TO_LIST";
export const DELETE_CARD_FROM_LIST = "DELETE_CARD_FROM_LIST";
export const MOVE_CARD_FROM_LIST = "MOVE_CARD_FROM_LIST";

// Quick Editor
export const GET_QUICK_EDITOR_STATE = "GET_QUICK_EDITOR_STATE";
export const TOGGLE_QUICK_EDITOR = "TOGGLE_QUICK_EDITOR";
export const CLOSE_QUICK_EDITOR = "CLOSE_QUICK_EDITOR";
export const UPDATE_CARD_TITLE = "UPDATE_CARD_TITLE";
